#!/usr/bin/env python3
"""Write App/Generated/ProviderSecrets.generated.swift from XAI_API_KEY / OPENAI_API_KEY.

Each key is XOR-masked with a fresh random mask per build, so the keys are not plain
strings in the binary. This is light obfuscation, not protection: anyone with the IPA
and some effort can recover them. The output file is gitignored; never commit it.
Prints nothing about the key values.
"""
import os
import pathlib
import secrets
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "App" / "Generated" / "ProviderSecrets.generated.swift"


def masked(value: str) -> tuple[list[int], list[int]]:
    raw = value.strip().encode("utf-8")
    mask = secrets.token_bytes(max(len(raw), 1))
    return [b ^ mask[i] for i, b in enumerate(raw)], list(mask)


def swift_array(name: str, data: list[int]) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"    private static let {name}: [UInt8] = [{body}]\n"


def main() -> int:
    required = [n for n in sys.argv[1:]]
    keys = {"xai": os.environ.get("XAI_API_KEY", ""), "openai": os.environ.get("OPENAI_API_KEY", "")}
    missing = [n for n in required if not keys.get(n, "").strip()]
    if missing:
        print(f"Missing required key(s): {', '.join(missing)}", file=sys.stderr)
        return 1

    xai, xai_mask = masked(keys["xai"])
    oai, oai_mask = masked(keys["openai"])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/generate_provider_secrets.py. Do not commit.\n"
        "import Foundation\n\n"
        "@objc(ProviderSecretsGenerated)\n"
        "final class ProviderSecretsGenerated: NSObject, ProviderSecretsSource {\n"
        + swift_array("a", xai)
        + swift_array("b", xai_mask)
        + swift_array("c", oai)
        + swift_array("d", oai_mask)
        + "\n"
        "    private static func reveal(_ bytes: [UInt8], _ mask: [UInt8]) -> String {\n"
        "        guard !bytes.isEmpty, bytes.count <= mask.count else { return \"\" }\n"
        "        var out = [UInt8](repeating: 0, count: bytes.count)\n"
        "        for i in 0..<bytes.count { out[i] = bytes[i] ^ mask[i] }\n"
        "        return String(decoding: out, as: UTF8.self)\n"
        "    }\n\n"
        "    static var xaiAPIKey: String { reveal(a, b) }\n"
        "    static var openAIAPIKey: String { reveal(c, d) }\n"
        "}\n"
    )
    print(f"Wrote {OUT.name} (xai: {'set' if xai else 'empty'}, openai: {'set' if oai else 'empty'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
